import AppKit
import Combine
import Vision

enum ClipboardContent: Equatable {
    case text(String)
    case image(Data)
}

struct ClipboardItem: Identifiable, Equatable {
    let id: UUID
    let content: ClipboardContent
    let date: Date
    var ocrText: String? = nil
    var isPinned: Bool = false

    init(id: UUID = UUID(), content: ClipboardContent, date: Date,
         ocrText: String? = nil, isPinned: Bool = false) {
        self.id = id
        self.content = content
        self.date = date
        self.ocrText = ocrText
        self.isPinned = isPinned
    }
}

/// A persistent text note. Lives in the Notes sub-tab. Not affected by
/// Clear-history on the Temp tab. Manually managed by the user.
struct Note: Identifiable, Equatable, Codable {
    let id: UUID
    var text: String
    let createdAt: Date
    var updatedAt: Date

    init(id: UUID = UUID(), text: String, createdAt: Date = Date(), updatedAt: Date? = nil) {
        self.id = id
        self.text = text
        self.createdAt = createdAt
        self.updatedAt = updatedAt ?? createdAt
    }
}

final class ClipboardManager: ObservableObject {
    @Published private(set) var history: [ClipboardItem] = []
    @Published private(set) var notes: [Note] = []
    @Published var isFrozen: Bool = false
    @Published var searchQuery: String = ""
    @Published var searchFocusRequest: Int = 0

    private var timer: Timer?
    private var lastChangeCount: Int
    private let maxHistory = 50
    private let pollInterval: TimeInterval = 0.5
    private let store = PersistenceStore()
    private var cancellables = Set<AnyCancellable>()

    static let imageExtensions: Set<String> = ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "tif", "heic", "webp"]
    private static let skipPasteboardTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    ]

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        history = store.load()
        notes = store.loadNotes()

        $history
            .dropFirst()
            .debounce(for: .seconds(1.0), scheduler: DispatchQueue.main)
            .sink { [weak self] items in
                self?.store.save(items)
            }
            .store(in: &cancellables)

        $notes
            .dropFirst()
            .debounce(for: .seconds(0.6), scheduler: DispatchQueue.main)
            .sink { [weak self] n in
                self?.store.saveNotes(n)
            }
            .store(in: &cancellables)
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func flushSave() {
        store.save(history)
        store.saveNotes(notes)
    }

    // MARK: - Notes

    var filteredNotes: [Note] {
        let q = searchQuery.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if q.isEmpty { return notes }
        return notes.filter { $0.text.lowercased().contains(q) }
    }

    @discardableResult
    func addNote(text: String) -> Note? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        let note = Note(text: trimmed)
        notes.insert(note, at: 0)
        return note
    }

    func updateNote(id: UUID, text: String) {
        guard let idx = notes.firstIndex(where: { $0.id == id }) else { return }
        notes[idx].text = text.trimmingCharacters(in: .whitespacesAndNewlines)
        notes[idx].updatedAt = Date()
    }

    func deleteNote(id: UUID) {
        notes.removeAll { $0.id == id }
    }

    /// Move a Temp item into Notes and remove it from clipboard history.
    @discardableResult
    func moveItemToNotes(_ item: ClipboardItem) -> Note? {
        let textToSave: String?
        switch item.content {
        case .text(let text):
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            textToSave = trimmed.isEmpty ? nil : trimmed
        case .image:
            let ocr = item.ocrText?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            textToSave = ocr.isEmpty ? nil : ocr
        }
        guard let text = textToSave, let note = addNote(text: text) else { return nil }
        remove(item)
        return note
    }

    func requestSearchFocus() {
        searchFocusRequest += 1
    }

    var filteredHistory: [ClipboardItem] {
        let query = searchQuery.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let base: [ClipboardItem]
        if query.isEmpty {
            base = history
        } else {
            base = history.filter { item in
                switch item.content {
                case .text(let text):
                    return text.lowercased().contains(query)
                case .image:
                    return item.ocrText?.lowercased().contains(query) ?? false
                }
            }
        }
        let pinned = base.filter { $0.isPinned }
        let unpinned = base.filter { !$0.isPinned }
        return pinned + unpinned
    }

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        if ClipboardManager.skipPasteboardTypes.contains(where: { types.contains($0) }) {
            return
        }

        if let imageData = readImageData(from: pasteboard) {
            insert(.image(imageData))
        } else if let text = pasteboard.string(forType: .string), !text.isEmpty {
            insert(.text(text))
        }
    }

    private func readImageData(from pasteboard: NSPasteboard) -> Data? {
        if let data = pasteboard.data(forType: .png) { return data }
        if let tiff = pasteboard.data(forType: .tiff),
           let png = ClipboardManager.pngData(fromTIFF: tiff) {
            return png
        }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL] {
            for url in urls where ClipboardManager.imageExtensions.contains(url.pathExtension.lowercased()) {
                if let image = NSImage(contentsOf: url),
                   let png = ClipboardManager.pngData(from: image) {
                    return png
                }
            }
        }
        return nil
    }

    static func pngData(fromTIFF tiff: Data) -> Data? {
        guard let bitmap = NSBitmapImageRep(data: tiff) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }

    static func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation else { return nil }
        return pngData(fromTIFF: tiff)
    }

    private func insert(_ content: ClipboardContent) {
        if let existingIdx = history.firstIndex(where: { $0.content == content }) {
            let existing = history.remove(at: existingIdx)
            let refreshed = ClipboardItem(
                id: existing.id, content: existing.content, date: Date(),
                ocrText: existing.ocrText, isPinned: existing.isPinned
            )
            history.insert(refreshed, at: 0)
            return
        }
        let newItem = ClipboardItem(content: content, date: Date())
        history.insert(newItem, at: 0)
        if case .image(let data) = content {
            performOCR(for: newItem.id, imageData: data)
        }
        enforceMaxHistory()
    }

    private func enforceMaxHistory() {
        while history.filter({ !$0.isPinned }).count > maxHistory {
            if let oldestIdx = history.lastIndex(where: { !$0.isPinned }) {
                history.remove(at: oldestIdx)
            } else {
                break
            }
        }
    }

    private func performOCR(for itemId: UUID, imageData: Data) {
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let nsImage = NSImage(data: imageData),
                  let cgImage = nsImage.cgImage(forProposedRect: nil, context: nil, hints: nil) else {
                return
            }
            let request = VNRecognizeTextRequest { request, _ in
                let observations = request.results as? [VNRecognizedTextObservation] ?? []
                let text = observations
                    .compactMap { $0.topCandidates(1).first?.string }
                    .joined(separator: "\n")
                DispatchQueue.main.async {
                    self?.updateOCR(for: itemId, text: text)
                }
            }
            request.recognitionLevel = .accurate
            request.usesLanguageCorrection = true
            let handler = VNImageRequestHandler(cgImage: cgImage, options: [:])
            try? handler.perform([request])
        }
    }

    private func updateOCR(for itemId: UUID, text: String) {
        if let idx = history.firstIndex(where: { $0.id == itemId }) {
            history[idx].ocrText = text
        }
    }

    func add(text: String) {
        guard !text.isEmpty else { return }
        insert(.text(text))
    }

    func add(imageData: Data) {
        insert(.image(imageData))
    }

    func clearHistory() {
        history.removeAll { !$0.isPinned }
    }

    func remove(_ item: ClipboardItem) {
        history.removeAll { $0.id == item.id }
    }

    func togglePin(_ item: ClipboardItem) {
        if let idx = history.firstIndex(where: { $0.id == item.id }) {
            history[idx].isPinned.toggle()
        }
    }

    func copy(_ content: ClipboardContent) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data):
            if let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        }
    }
}
